blank_issues_enabled: false
contact_links:
  - name: Discord Chat Support
    url: https://discord.gg/ztkBqR2
    about: Realtime support & chat with the BookStack community and the team.

  - name: Debugging & Common Issues
    url: https://www.bookstackapp.com/docs/admin/debugging/
    about: Find details on how to debug issues and view common issues with their resolutions.

  - name: Official Support Plans
    url: https://www.bookstackapp.com/support/
    about: View our official support plans that offer assured support for business.

  - name: 4xx Errors Of API
    url: http://localhost:8080/books/faq-4xx-errors
    about: Ошибки 4хх при интеграции API

    
  - name: 5xx Errors Of API
    url: http://localhost:8080/books/faq-5xx-errors
    about: Ошибки 5хх при интеграции API
